- hosts: kubernetes
  remote_user: netapp
  gather_facts: false
  vars_files:
    - ../config/internet_gateway.yaml
  tasks:
    - name: "Add static internet gatway route to all nodes"
      command: route add default gw "{{ internet_gateway }} {{ interface }}"
      become: true
      ignore_errors: yes #if routes already exists ignore that
