- hosts: kubernetes
  remote_user: netapp
  gather_facts: false

  tasks:
    - name: "Add static internet gatway route to all nodes"
      command: route add default gw 172.20.218.10 ens160
      become: true
      ignore_errors: yes #if routes already exists ignore that
