- hosts: k8s*kubespray*
  remote_user: netapp
  vars_files:
    - ../config/git_config.yaml
  vars:
    install_dir: /home/netapp/kubespray/
  tasks:
    - name: "Set a git account"
      command: "git config --global user.name {{ git_user }}"
      become: true

    - name: "Set a git mail"
      command: "git config --global user.email {{ git_mail }}"
      become: true

    - name: "Clone Kubespray from git to {{ inventory_hostname }} into {{ install_dir }}"
      command: "git clone {{kubespray_url}} {{ install_dir }}"
      become: true
      ignore_errors: yes #if folder already exists ignore that

    - name: "Install kubespray requirements"
      command: "pip3 install -r {{ install_dir }}requirements.txt"
      become: true
    
    - name: "Copy kubespray host inventory"
      command: "cp -rfp {{ install_dir }}inventory/sample {{ install_dir }}inventory/k8s-cluster"
      become: true

    - name: "Copy kubespray hosts.ini to kubespray host"
      copy:
        src: ../config/hosts.ini
        dest: "{{ install_dir }}inventory/k8s-cluster/hosts.ini"
        owner: netapp
        group: netapp
      become: true
      run_once: true

    - name: "Copy private key to kubespray host"
      copy:
        src: /home/netapp/.ssh/id_rsa
        dest: /home/netapp/.ssh/id_rsa
        owner: netapp
        group: netapp
        mode: 0600
      become: true
      run_once: true

    - name: "Copy private key to kubespray host for root"
      copy:
        src: /home/netapp/.ssh/id_rsa
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: 0600
      become: true
      run_once: true

    - name: "Test ping"
      shell: " ansible -i /home/netapp/kubespray/inventory/k8s-cluster/hosts.ini all -m ping -e 'ansible_python_interpreter=/usr/bin/python3' --ssh-common-args='-o StrictHostKeyChecking=no'"

    - name: "Run kubespray remotely"
      shell: "ansible-playbook -i /home/netapp/kubespray/inventory/k8s-cluster/hosts.ini --become --become-user=root /home/netapp/kubespray/cluster.yml -e 'ansible_python_interpreter=/usr/bin/python3' --ssh-common-args='-o StrictHostKeyChecking=no'"


