- hosts: localhost
  tasks:
    - debug: 
       msg: "Starting deploying full cluster"

# Some commencts to 'include' vs. 'import_playbook':
# Inlcude is dynamic. That means all playbooks and tasks are processed at execution time
# Import is static. All statements are pre-processed
# So if a playbook depends on the output of a prior playbook then this will only work with dynamic include

- name: Create VMware VM clones
  include: 1-vmware-playbooks/clone-devOps-vm.yaml

- name: Setup VMs
  include: 2-linux-basic-playbooks/change-hostnames.yaml

- name: Install iSCSI Utils
  include: 2-linux-basic-playbooks/install-iscsi-utils.yaml

- name: Install Kubespray and rollout Kubernetes cluster
  include: 2-linux-basic-playbooks/install-kubespray.yaml

- name: Create static route for internet access
  include: 2-linux-basic-playbooks/add-route-internet-gateway.yaml

- name: Setup kubectl locally and copy kube config
  include: 3-kubernetes-playbooks/install-kubectl-locally.yaml

- name: Setup ONTAP SVM
  include: 4-ontap-playbooks/setup-ontap-svm.yaml

- name: Add iSCSI IQNs to the ONTAP SVM
  include: 4-ontap-playbooks/add-isci-iqn.yaml

- name: Install Trident
  include: 5-trident-playbooks/install-trident.yaml

- name: Install Load Balancer
  include: 6-kubernetes-eco-system/install-loadbalancer.yaml

- name: Print access details
  include: 6-kubernetes-eco-system/show-access-details.yaml 
