# Check documentation here:
# https://docs.ansible.com/ansible/latest/vmware/vmware_scenarios.html

# Assumes that ansible hosts are located in /etc/ansible/hosts and that there is a section in that file with [kubernetes]

- name:  Clone a virtual machine from Linux template and customize
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../config/vcenter_vars.yaml
    - ../config/k8s-host-list.yaml
  tasks:
    - set_fact:
       template_name: "{{ vm_template }}"
    - name: "Clone from template - {{ template_name }}"
      async: 1000
      poll: 5
      with_items: "{{ k8shostlist }}"
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        name: "{{ item }}"
        template: "{{ template_name }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ folder }}"
        state: poweredon
        cluster: "{{ cluster }}"
        resource_pool: "{{ resource_pool }}"
        wait_for_ip_address: true
      register: clone_facts

    - name: "Add to ansible hosts file"
      with_items: "{{ clone_facts.results}}"
      lineinfile:
        dest: /etc/ansible/hosts
        insertafter: '^\[kubernetes]'
        line: '{{item.instance.hw_name}} ansible_host={{item.instance.ipv4}}'
      become: true
      ignore_errors: yes 
      no_log: True

    - name: "Clean up pre-existing kubespray hosts file if exists"
      file:
         path: ../config/hosts.ini
         state: absent
        
    - name: "Prepate kubespray hosts file"
      copy:
        src: ../config/templates/kubespray_hosts.ini
        dest: ../config/hosts.ini

    - name: "Add all hosts to kubespray hosts file"
      with_items: "{{  clone_facts.results}}"
      when: '"kubespray" not in item.instance.hw_name'
      lineinfile:
        dest: ../config/hosts.ini
        insertafter: '^\[all]'
        line: '{{item.instance.hw_name}}     ansible_host={{item.instance.ipv4}} ip={{item.instance.ipv4}}'
      ignore_errors: yes

    - name: "Add master hosts to kubespray hosts file"
      with_items: "{{ k8shostlist}}"
      when: '"master" in item'
      lineinfile:
        dest: ../config/hosts.ini
        insertafter: '^\[kube-master]'
        line: '{{item}}'
      ignore_errors: yes

    - name: "Add worker nodes to kubespray hosts file"
      with_items: "{{ k8shostlist}}"
      when: '"node" in item'
      lineinfile:
        dest: ../config/hosts.ini
        insertafter: '^\[kube-node]'
        line: '{{item}}'
      ignore_errors: yes

    - name: "Add hosts for etcd to kubespray hosts file"
      with_items: "{{ clone_facts.results }}"
      when: '"master" in item.instance.hw_name'
      lineinfile:
        dest: ../config/hosts.ini
        insertafter: '^\[etcd]'
        line: '{{item.instance.hw_name}} ansible_host={{item.instance.ipv4}}'
      ignore_errors: yes

