# Under work
# Check documentation here:
# https://docs.ansible.com/ansible/latest/vmware/vmware_scenarios.html

- name:  Clone a virtual machine from Linux template and customize
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../config/vcenter_vars.yml
    - ../config/k8s-host-list.yml
  tasks:
    - set_fact:
       template_name: "ubuntu-devops-template"
    - name: "Clone from template - {{ template_name }}"
      with_items: "{{ k8shostlist }}"
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        name: "{{ item }}"
        template: "{{ template_name }}"
        datacenter: "Stuttgart"
        folder: /Stuttgart/vm/Productions-Cluster
        state: poweredon
        cluster: "Production-Cluster"
        resource_pool: "DevOps"
        wait_for_ip_address: true
      register: clone_facts
    #- debug:
    #   msg: "Debug clone_facts: {{ clone_facts }}"


#    - name: "Add cloned VMs to Ansible in-memory inventory"
#      with_items: "{{ k8shostlist }}"
#      add_host:
#        name: "{{ item }}"
#        groups: kubernetes

#    - name: "Print cloned name"
#      debug: 
#        msg: "item={{item.instance.hw_name}} " 
#      with_items: "{{clone_facts.results}}"

    - name: "Add to ansible hosts file"
      with_items: "{{ clone_facts.results}}"
      lineinfile:
        dest: /etc/ansible/hosts
        insertafter: '^\[kubernetes]'
        line: '{{item.instance.hw_name}} ansible_host={{item.instance.ipv4}}'
      become: true
      ignore_errors: yes #if routes already exists ignore that

