---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ..\config\ontap_vars.yaml
  vars:
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  name: Cleanup SVM
  tasks:
  - name: Delete SVM
    na_ontap_svm:
      state: absent
      name: "{{ vserver }}"
      <<: *login

