# Check install guide at https://netapp-trident.readthedocs.io

- name: Download, configure and install NetApp Trident
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../config/trident_vars.yaml
  tasks:
    - name: Clean temp-files/ path if existing
      file:
        state: absent
        path: ../temp-files/

    - name: Create temp-files/ directory
      file:
        path: ../temp-files
        state: directory

    - name: "Download Trident Version {{ trident_version_full }}"
      get_url:
        url: "https://github.com/NetApp/trident/releases/download/v{{ trident_version_full }}/trident-installer-{{ trident_version_full }}.tar.gz"
        dest: ../temp-files/

    - name: Extract Trident to ../temp-files/
      unarchive:
        src: "../temp-files/trident-installer-{{ trident_version_full }}.tar.gz"
        dest: "../temp-files/"
   
    - name: Move install directory
      command: "mv -f ../temp-files/trident-installer ../temp-files/trident-installer-{{ trident_version }}"

    - name: Uninstall pre-existing Trident installation (if existing)
      command: "../temp-files/trident-installer-{{ trident_version }}/tridentctl uninstall -n trident"
      ignore_errors: true

    - name: Install Trident
      command: "../temp-files/trident-installer-{{ trident_version }}/tridentctl install -n trident"

    - name: Create ONTAP NFS v3 backend
      shell: "../temp-files/trident-installer-{{ trident_version }}/tridentctl create backend -f ../config/nfs-v3-backend.json -n trident"

    - name: Create ONTAP iSCSI backend
      shell: "../temp-files/trident-installer-{{ trident_version }}/tridentctl create backend -f ../config/iscsi-backend.json -n trident"

    - name: Create HCI/Solidfire iSCSI backend
      shell: "../temp-files/trident-installer-{{ trident_version }}/tridentctl create backend -f ../config/iscsi-backend-solidfire.json -n trident"

    - name: Create ONTAP NFS v3 Kubernetes Storage class
      shell: "kubectl create -f ../config/storageclass-nfs.yaml"
      ignore_errors: true

    - name: Create ONTAP iSCSI Kubernetes Storage class
      shell: "kubectl create -f ../config/storageclass-iscsi.yaml"
      ignore_errors: true

    - name: Create HCI/Solidfire iSCSI Kubernetes Storage class
      shell: "kubectl create -f ../config/storageclass-iscsi-solidfire.yaml"
      ignore_errors: true

    - name: Clean potential old tridentctl versions
      file:
        state: absent
        path: "/usr/local/bin/tridentctl"
      become: true

    - name: Copy tridentctl to /usr/local/bin
      copy:
        src: "../temp-files/trident-installer-{{ trident_version }}/tridentctl"
        dest: /usr/local/bin/
        mode: 0755
      become: true
