- name: Uninstall NetApp Trident
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../config/trident_vars.yaml
  tasks:

    - name: Uninstall Trident
      command: "../temp-files/trident-installer-{{ trident_version }}/tridentctl uninstall -n trident --all"
