hostname: tcl1.stuttgart.local
username: admin
password: adminpassword
vserver: svm_kubernetes

# used for svm root volume
aggr: node1_data_sas

### Ports & Networking
# nfs & mgmt will be put on homeport & homenode1
# iscsi will get a lif on homenode1 and homenode2
homeport: a0a-100
homenode1: node1-8040
homenode2: node2-8040

mgmtaddress: 172.20.209.176
nfsaddress: 172.20.209.177

iscsi1: 172.20.209.178
# iscsi1 lif will be put on homenode1

iscsi2: 172.20.209.179
# iscsi2 lif will be put on homenode2

# list of aggregates where trident can place volumes
aggrlist: [node1_data_sas, node2_data_sas]

vsadminpassword: vsadminpassword

# default export policy
exportpolicy: 0.0.0.0/0
