apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gold-nfs-v3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: netapp.io/trident
parameters:
  backendType: "ontap-nas"
  provisioningType: "thin"

